### ISSUE TITLE
It's not used.

### ISSUE THREAD

**Issue by Yu-Xiao-Sheng** [allan2/dotenvy#138] opened 2024-11-06 08:45 UTC
find lastest version dotenvy 0.15.7 by https://crates.io/. so install to my project : 

dotenvy = { version = "0.15.7", features = ["macros"] }

but，cargo build error :

versions that meet the requirements `^0.15.7` (locked to 0.15.7) are: 0.15.7

the package `base` depends on `dotenvy`, with features: `macros` but `dotenvy` does not have these features.

failed to select a version for `dotenvy` which could resolve this conflict

stderr:

**Comment by digitalcortex** [comment] 2024-11-10 09:23
How "It's not used" title is related to the problem you're describing? What is not used?

**Comment by allan2** [comment] 2024-11-10 09:32
The list of features for 0.15.7 is [here](https://docs.rs/crate/dotenvy/0.15.7/features).

"macros" is part of upcoming version which is still in development.

**Comment by Dylan-DPC** [comment] 2024-11-11 07:55
Closing this as it's not a bug.

**Closed as not planned by Dylan-DPC** 2024-11-11 07:55 UTC
